<?php

/** @var \Instagram\Api\Block\Widget\InstagramCurl  $block */
?>
<?php $curldata = $block->getCurlData(); 
$result = json_decode($curldata, true);
echo "<div id='fancybox_gallary'>";
	foreach($result["data"] as $post )
	{ 
	  $media_url = isset($post["media_url"]) ? $post["media_url"] : "";
	  $permalink = isset($post["permalink"]) ? $post["permalink"] : "";
	  $id =     isset($post["id"]) ? $post["id"] : "";
	  echo "<a id='{$id}' data-fancybox='images' data-type='iframe' href='{$permalink}' class='fancyboximg' data-width='320' 
	  data-height='400' data-src='$media_url' ><img src='{$media_url}' class='instagramapimg'/></a>";

	  echo "<div id='{$id}' class='video-link' style='display:none'>
	  <a  class='link-id-videochat' href='{$permalink}' target='_blank'>View Url</a></div>";
	  
	}
echo "</div>"

?>
<script type="text/javascript">
    require([
            'jquery',
            'fancybox',
             'domReady!',
        ],
        function($) {
			$('[data-fancybox="images"]').fancybox({
				afterLoad : function(instance, current) {
		  			console.log(instance, current, 'kkkkkkkk');
                        let instanceId = instance.$trigger.attr('id');
						console.log($('#'+instanceId + '.video-link'), 'instanceId')
						current.$content.append( $('#'+instanceId + '.video-link').clone(true).show());
						console.info(current.$content);
					}
				});	
				 });
</script>