<?php

/** @var \Instagram\Api\Block\Widget\InstagramCurl  $block */
?>
<?php $curldata = $block->getCurlData(); 

$result = json_decode($curldata, true);


foreach($result["data"] as $post)
{ 
  $media_url = isset($post["media_url"]) ? $post["media_url"] : "";
  $permalink = isset($post["permalink"]) ? $post["permalink"] : "";
  echo "<a  data-fancybox='images' data-type='iframe' href='{$permalink}'><img src='{$media_url}' class='instagramapimg'/></a>";
    
}
?>
<script type="text/javascript">
    require([
            'jquery',
            'fancybox'
        ],
        function($) {
       
        });
</script>
